name: "tag-action"
description: "Tag Action"
author: "Henning Dieterichs"
branding:
    icon: "tag"
    color: "blue"
inputs:
    github_token:
        required: true
        description: 'Pass "${{ secrets.GITHUB_TOKEN }}"'
    tag:
        required: true
        description: "The tag name"
    tag_prefix:
        required: false
        description: "An optional prefix"
    create:
        required: false
        default: "false"
        description: 'Pass "true" to create the tag if it exists.'
    fail_if_exists:
        required: false
        default: "false"
        description: 'Pass "true" fail if the tag exists.'
outputs:
    exists:
        description: 'Indicates whether the tag existed. Is "true" or "false".'
runs:
    using: "node12"
    main: "dist/index.js"
